# User config
author: "SOGIHYEON"
tagline: "Portfolio"
description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "statios@kakao.com"
#linkedin: "https://www.linkedin.com/"
#twitter: "https://twitter.com/"
github: "https://github.com/statios"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
